from petisco.base.domain.errors.unknown_error import UnknownError


class UseCaseUncontrolledError(UnknownError):
    pass
